const ADD_TASK = "ADD_TASK"
const EDIT_TASK = "EDIT_TASK"
const DELETE_TASK = "DELETE_TASK"
const ARCHIVE_TASK = "ARCHIVE_TASK"
const UNARCHIVE_TASK = "UNARCHIVE_TASK"

const ADD_PROJECT = "ADD_TASK"
const EDIT_PROJECT = "EDIT_TASK"
const DELETE_PROJECT = "DELETE_TASK"
const ARCHIVE_PROJECT = "ARCHIVE_TASK"
const UNARCHIVE_PROJECT = "UNARCHIVE_TASK"

const GET_PROJECTS = "GET_PROJECTS"
const GET_TASKS = "GET_TASKS"

export {
    ADD_TASK, EDIT_TASK, DELETE_TASK, ARCHIVE_TASK, UNARCHIVE_TASK, ADD_PROJECT,
    EDIT_PROJECT, DELETE_PROJECT, ARCHIVE_PROJECT, UNARCHIVE_PROJECT, GET_PROJECTS, GET_TASKS
}